name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven
      - name: Maven install, test skipped
        run: mvn install -DskipTests
      - name: Maven test
        run: mvn test
      - name: Run Gradle exammple
        run: ./gradlew build run --no-daemon
        working-directory: examples/gradle
      - name: Run Gradle ICU exammple
        run: ./gradlew build run --no-daemon
        working-directory: examples/gradle-icu



